---
- name: Install helm (latest v3)
  ansible.builtin.shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    executable: /bin/bash
    creates: /usr/local/bin/helm
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
