---
- name: Install helm
  ansible.builtin.shell: |
    set -e
    tmp_dir="/tmp/harvester-ci/helm-tmp"
    mkdir -p $tmp_dir
    pushd $tmp_dir
    curl -sL https://get.helm.sh/helm-v3.16.2-linux-amd64.tar.gz -o helm.tar.gz
    tar xzvf helm.tar.gz
    cp linux-amd64/helm /usr/local/bin/helm
    popd
    rm -rf $tmp_dir
  args:
    executable: /bin/bash
    creates: /usr/local/bin/helm
