---
- name: Install yq (package)
  ansible.builtin.package:
    name:
    - yq
  when: ansible_distribution == "openSUSE Leap"

- name: Install yq (github)
  ansible.builtin.get_url:
    url: "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
    dest: /usr/local/bin/yq
    mode: '0755'
  when: ansible_distribution == "Ubuntu"
