---
# tasks file for common
- name: Install common packages
  ansible.builtin.package:
    name:
    - git
    - ansible
    - vim
    - jq
    - make
    - sysstat
    - gdisk
    - fio

- ansible.builtin.include_tasks: _yq.yml
- ansible.builtin.include_tasks: _k9s.yml
- ansible.builtin.include_tasks: _helm.yml
  
- name: Install kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ common_kubectl_version  }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Add CI users
  ansible.builtin.user:
    name: "{{ item }}"
    generate_ssh_key: yes
    shell: /bin/bash
  loop: "{{ common_ci_users }}"

- name: Add authorized_keys
  authorized_key:
    user: "{{ common_login_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - public_keys/*
# - name: Generate ssh keypair for CI users
#   openssh_keypair:
#     user: "{{ common_login_user }}"
#     state: present
#     key: "{{ lookup('file', item) }}"
#   loop: "{{ common_ci_users }}"

- name: add ssh client config
  ansible.builtin.copy:
    src: "harvester-ci.conf"
    dest: "/etc/ssh/ssh_config.d/harvester-ci.conf"
    mode: '0644'
