---
- name: Install httpd packages
  ansible.builtin.package:
    name:
    - nginx
  notify:
    - restart httpd

- ansible.builtin.set_fact:
    httpd_group: "nginx"
  when: ansible_distribution == "openSUSE Leap"

- ansible.builtin.set_fact:
    httpd_group: "www-data"
  when: ansible_distribution == "Ubuntu"

- name: Create artifacts directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    group: "{{ httpd_group }}"
    mode: '0775'
  loop:
    - "/srv/www/htdocs/harvester/rke2"
    - "/srv/www/htdocs/harvester/artifacts"
    - "/srv/www/htdocs/harvester/workflows"
    - "/srv/www/htdocs/harvester/images"

- ansible.builtin.include_tasks: _opensuse.yml
  when: ansible_distribution == "openSUSE Leap"

- ansible.builtin.include_tasks: _ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: add users to nginx group
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - "{{ httpd_group }}"
    append: yes
  loop: "{{ httpd_nginx_group_users }}"

- name: Create scripts
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    mode: '0755'
  loop: "{{ httpd_ci_scripts }}"

- name: Download and serve images
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/srv/www/htdocs/harvester/images/{{ item.filename }}"
    mode: '0664'
  loop: "{{ httpd_default_images }}"
