---
- ansible.builtin.include_tasks: _opensuse.yml
  when: ansible_distribution == "openSUSE Leap"

- ansible.builtin.include_tasks: _ubuntu.yml
  when: ansible_distribution == "Ubuntu"


- name: add users to libvirt group
  user:
    name: "{{ item }}"
    groups:
      - libvirt
    append: yes
  loop: "{{ vagrant_libvirt_group_users }}"

- name: export LIBVIRT DEFAULT URI
  lineinfile:
    dest: "/home/{{ item.0 }}/.bashrc"
    line: "export {{ item.1.key }}={{ item.1.value }}"
    regexp: '^#?\s*{{ item.1.key }}='
    state: present
  with_nested:
    - "{{ vagrant_libvirt_group_users }}"
    - - { key: LIBVIRT_DEFAULT_URI,  value: 'qemu:///system' }

- name: allow run sudo iptables without password
  community.general.sudoers:
    name: "{{ item }}"
    state: present
    user: "{{ item }}"
    commands: /usr/sbin/iptables
  loop: "{{ vagrant_sudo_users }}"

- name: add the script to enable libvirt network route
  ansible.builtin.copy:
    src: enable-libvirt-network-route.sh 
    dest: /usr/sbin/enable-libvirt-network-route.sh
    mode: '0755'
