---
# tasks file for docker
- ansible.builtin.include_tasks: _opensuse.yml
  when: ansible_distribution == "openSUSE Leap"

- ansible.builtin.include_tasks: _ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - docker
    append: yes
  loop: "{{ docker_group_users }}"

- meta: flush_handlers
  
- name: Create a local registry
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: unless-stopped
    ports:
      - "5000:5000"
  