---
# tasks file for docker
- name: Install docker
  package:
    name: docker
  notify:
    - restart docker

- name: add users to docker group
  user:
    name: "{{ item }}"
    groups:
      - docker
    append: yes
  loop: "{{ docker_group_users }}"

# this is bad, we overwrite the the whole file
- name: config docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart docker
