
- hosts: harvester_ci_vm
  become: yes
  roles:
    - role: common
      vars:
        common_login_user: "{{ ansible_user }}"
        common_ci_users: ["{{ ansible_user }}", "github", "github2", "github3"]
    - role: docker
      vars:
        docker_group_users: ["{{ ansible_user }}", "github", "github2", "github3"]
        docker_insecure_registries: ["172.17.0.1:5000"]
    - role: vagrant
      vars:
        vagrant_libvirt_group_users: ["{{ ansible_user }}", "github", "github2", "github3"]
        # do not add the login user to the sudoers, it will break the passwordless power
        vagrant_sudo_users: ["github", "github2", "github3"]
    - role: httpd
      vars:
        httpd_nginx_group_users: ["{{ ansible_user }}", "github", "github2", "github3"]
