---
# defaults file for httpd

# add these users to nginx group
httpd_nginx_group_users: []

httpd_ci_scripts:
- file: get-rke2.sh
  dest: /srv/www/htdocs/harvester/rke2/get-rke2.sh
- file: get-harvester.sh
  dest: /srv/www/htdocs/harvester/artifacts/get-harvester.sh

httpd_default_images:
- url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64-disk-kvm.img"
  filename: "jammy-server-cloudimg-amd64-disk-kvm.img"
- url: "https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.5/images/openSUSE-Leap-15.5.x86_64-NoCloud.qcow2"
  filename: "openSUSE-Leap-15.5.x86_64-NoCloud.qcow2"
